/**
 * Prepare clasp + Apps Script IDs for an environment.
 *
 * Reads config/env.json (gitignored; copy from config/env.example.json).
 * Writes:
 *  - .clasp.json          (scriptId for clasp push/deploy)
 *  - src/Config_Env.js    (SPREADSHEET_ID / drive / script constants for GAS)
 *  - .clasp-dev.json / .clasp-prod.json (kept in sync for convenience)
 *
 * Usage: node scripts/prepare-env.js <dev|prod>
 */
const fs = require('fs');
const path = require('path');

const envName = String(process.argv[2] || '').trim().toLowerCase();
if (envName !== 'dev' && envName !== 'prod') {
  console.error('Usage: node scripts/prepare-env.js <dev|prod>');
  process.exit(1);
}

const root = path.join(__dirname, '..');
const envPath = path.join(root, 'config', 'env.json');
const examplePath = path.join(root, 'config', 'env.example.json');

if (!fs.existsSync(envPath)) {
  console.error('Missing config/env.json');
  console.error('Copy config/env.example.json -> config/env.json and fill in your IDs.');
  if (fs.existsSync(examplePath)) {
    console.error('Example exists at: config/env.example.json');
  }
  process.exit(1);
}

let allEnv;
try {
  allEnv = JSON.parse(fs.readFileSync(envPath, 'utf8'));
} catch (error) {
  console.error('Could not parse config/env.json:', error.message);
  process.exit(1);
}

const selected = allEnv[envName];
const other = allEnv[envName === 'dev' ? 'prod' : 'dev'];
if (!selected || typeof selected !== 'object') {
  console.error('config/env.json is missing a "' + envName + '" block.');
  process.exit(1);
}

function requireId(block, key, label) {
  const value = String((block && block[key]) || '').trim();
  if (!value || value.indexOf('YOUR_') === 0) {
    console.error('Set ' + label + ' in config/env.json before using ' + envName + '.');
    process.exit(1);
  }
  return value;
}

const scriptId = requireId(selected, 'scriptId', envName + '.scriptId');
const spreadsheetId = requireId(selected, 'spreadsheetId', envName + '.spreadsheetId');
const driveId = String(selected.driveId || '').trim();
if (!driveId || driveId.indexOf('YOUR_') === 0) {
  console.warn('Warning: ' + envName + '.driveId is empty/placeholder. Logo uploads will need DRIVE_ID in SETTINGS.');
}
const deploymentIdRaw = String(selected.deploymentId || '').trim();
const deploymentId = (!deploymentIdRaw || deploymentIdRaw.indexOf('YOUR_') === 0) ? '' : deploymentIdRaw;
if (!deploymentId) {
  console.warn('Warning: ' + envName + '.deploymentId is empty. Set it after the first web app deploy so Settings → Publish works.');
}

const devScriptId = String((allEnv.dev && allEnv.dev.scriptId) || '').trim();
const prodScriptId = String((allEnv.prod && allEnv.prod.scriptId) || '').trim();
const devSpreadsheetId = String((allEnv.dev && allEnv.dev.spreadsheetId) || '').trim();
const prodSpreadsheetId = String((allEnv.prod && allEnv.prod.spreadsheetId) || '').trim();
const otherDriveId = String((other && other.driveId) || '').trim();

function claspConfig(id) {
  return {
    scriptId: id,
    rootDir: 'src',
    scriptExtensions: ['.js', '.gs'],
    htmlExtensions: ['.html'],
    jsonExtensions: ['.json'],
    filePushOrder: [],
    skipSubdirectories: false
  };
}

fs.writeFileSync(path.join(root, '.clasp.json'), JSON.stringify(claspConfig(scriptId), null, 2) + '\n');

function jsString(value) {
  return JSON.stringify(String(value || ''));
}

const configEnvJs = [
  '/**',
  ' * AUTO-GENERATED by scripts/prepare-env.js — do not edit by hand.',
  ' * Source: config/env.json (' + envName + ')',
  ' */',
  'var LSC_ENV = ' + jsString(envName) + ';',
  'var SPREADSHEET_ID = ' + jsString(spreadsheetId) + ';',
  'var LSC_DRIVE_ID = ' + jsString(driveId.indexOf('YOUR_') === 0 ? '' : driveId) + ';',
  'var LSC_SCRIPT_ID = ' + jsString(scriptId) + ';',
  'var LSC_DEV_SCRIPT_ID = ' + jsString(devScriptId.indexOf('YOUR_') === 0 ? '' : devScriptId) + ';',
  'var LSC_PROD_SCRIPT_ID = ' + jsString(prodScriptId.indexOf('YOUR_') === 0 ? '' : prodScriptId) + ';',
  'var LSC_DEV_SPREADSHEET_ID = ' + jsString(devSpreadsheetId.indexOf('YOUR_') === 0 ? '' : devSpreadsheetId) + ';',
  'var LSC_PROD_SPREADSHEET_ID = ' + jsString(prodSpreadsheetId.indexOf('YOUR_') === 0 ? '' : prodSpreadsheetId) + ';',
  'var LSC_DEV_DRIVE_ID = ' + jsString((allEnv.dev && allEnv.dev.driveId && String(allEnv.dev.driveId).indexOf('YOUR_') !== 0) ? allEnv.dev.driveId : '') + ';',
  'var LSC_PROD_DRIVE_ID = ' + jsString((allEnv.prod && allEnv.prod.driveId && String(allEnv.prod.driveId).indexOf('YOUR_') !== 0) ? allEnv.prod.driveId : '') + ';',
  'var LSC_DEPLOYMENT_ID = ' + jsString(deploymentId) + ';',
  'var LSC_DEV_DEPLOYMENT_ID = ' + jsString((allEnv.dev && allEnv.dev.deploymentId && String(allEnv.dev.deploymentId).indexOf('YOUR_') !== 0) ? allEnv.dev.deploymentId : '') + ';',
  'var LSC_PROD_DEPLOYMENT_ID = ' + jsString((allEnv.prod && allEnv.prod.deploymentId && String(allEnv.prod.deploymentId).indexOf('YOUR_') !== 0) ? allEnv.prod.deploymentId : '') + ';',
  ''
].join('\n');

fs.writeFileSync(path.join(root, 'src', 'Config_Env.js'), configEnvJs);

console.log('Prepared ' + envName + ' environment:');
console.log('  scriptId      = ' + scriptId);
console.log('  spreadsheetId = ' + spreadsheetId);
console.log('  driveId       = ' + (driveId && driveId.indexOf('YOUR_') !== 0 ? driveId : '(not set)'));
console.log('  deploymentId  = ' + (deploymentId || '(not set)'));
console.log('Wrote .clasp.json and src/Config_Env.js');
