/**
 * Utils_DB.gs
 * Generic CRUD operations utilizing Advanced Sheets Service (batchUpdate).
 * Safely ignores and preserves formula-driven columns marked with a '*' in the header.
 *
 * SPREADSHEET_ID / LSC_DRIVE_ID come from Config_Env.js (generated by npm run use:dev|use:prod).
 *
 * Sheets API quota: ~60 read requests / minute / user. We cache short-lived reads and
 * retry with backoff when quota is briefly exceeded.
 */

/** Request-scoped memo (one Apps Script execution). */
var __dbMemCache = {};
/** Short cross-request TTL for repeated navigation bursts. */
var DB_READ_CACHE_TTL_SEC = 20;

const DB = {

  /**
   * Reads all records and maps them to an array of objects.
   * Strips '*' from header names for clean frontend usage.
   */
  read: function (sheetName) {
    const cacheKey = 'read:' + sheetName;
    const cached = this._cacheGet(cacheKey);
    if (cached) return cached;

    const range = `${sheetName}!A1:Z`;
    const response = this._sheetsValuesGet(range);
    const records = this._rowsToRecords(response.values);
    this._cachePut(cacheKey, records);
    return records;
  },

  /**
  * Fetches multiple sheets in a single network batch call for high performance.
  * @param {string[]} sheetNames Array of sheet titles to fetch.
  * @returns {Object} An object mapping sheet names to arrays of record objects.
  */
  batchRead: function (sheetNames) {
    const names = (sheetNames || []).slice();
    const cacheKey = 'batch:' + names.slice().sort().join('|');
    const cached = this._cacheGet(cacheKey);
    if (cached) return cached;

    // Reuse any per-sheet mem entries already loaded in this execution
    const missing = [];
    const result = {};
    names.forEach((name) => {
      const one = this._cacheGet('read:' + name);
      if (one) result[name] = one;
      else missing.push(name);
    });

    if (missing.length) {
      const ranges = missing.map(name => `${name}!A1:AZ`);
      const response = this._sheetsValuesBatchGet(ranges);
      const valueRanges = response.valueRanges || [];
      missing.forEach((sheetName, idx) => {
        const records = this._rowsToRecords(valueRanges[idx] ? valueRanges[idx].values : []);
        result[sheetName] = records;
        this._cachePut('read:' + sheetName, records);
      });
    }

    this._cachePut(cacheKey, result);
    return result;
  },

  /**
   * Creates a record targeting specific cells to preserve row formulas.
   */
  create: function (sheetName, recordObj) {
    const meta = this._getSheetMeta(sheetName);
    const headers = meta.headers;
    const newRow = meta.nextRow;

    recordObj.createdAt = new Date().toISOString();
    recordObj.updatedAt = new Date().toISOString();

    const dataRanges = this._buildUpdateRanges(sheetName, newRow, headers, recordObj);

    Sheets.Spreadsheets.Values.batchUpdate({
      valueInputOption: 'USER_ENTERED',
      data: dataRanges
    }, SPREADSHEET_ID);

    this._invalidateSheet(sheetName);
    recordObj._rowNumber = newRow;
    return recordObj;
  },

  /**
   * Updates an existing record by looking up its row number via ID.
   */
  update: function (sheetName, recordId, updateObj) {
    const meta = this._getSheetMeta(sheetName);
    const records = this._rowsToRecords(meta.values);
    const headers = meta.headers;

    // Find the record matching the primary ID
    const target = records.find(r =>
      r.memberId === recordId ||
      r.staffId === recordId ||
      r.expenseId === recordId ||
      r.paymentId === recordId ||
      r.userId === recordId ||
      r.id === recordId
    );

    // Fallback if recordId was explicitly passed as a numeric row number
    let rowNumber = target ? target._rowNumber : Number(recordId);

    if (!rowNumber || isNaN(rowNumber)) {
      throw new Error(`Record with ID ${recordId} not found or invalid row for update in ${sheetName}.`);
    }

    updateObj.updatedAt = new Date().toISOString();

    const dataRanges = this._buildUpdateRanges(sheetName, rowNumber, headers, updateObj);

    Sheets.Spreadsheets.Values.batchUpdate({
      valueInputOption: 'USER_ENTERED',
      data: dataRanges
    }, SPREADSHEET_ID);

    this._invalidateSheet(sheetName);
    return true;
  },

  /**
   * Deletes a record from a sheet based on its unique ID field (e.g., memberId, staffId, expenseId).
   */
  remove: function (sheetName, recordId) {
    const records = this.read(sheetName);

    // Find the record matching the primary ID
    const target = records.find(r =>
      r.memberId === recordId ||
      r.staffId === recordId ||
      r.expenseId === recordId ||
      r.paymentId === recordId ||
      r.userId === recordId ||
      r.id === recordId
    );

    if (!target || !target._rowNumber) {
      throw new Error(`Record with ID ${recordId} not found in ${sheetName}.`);
    }

    const rowNumber = target._rowNumber;

    // 100% Advanced Sheets Service: Fetch sheet metadata directly via REST API
    const ssMeta = this._withSheetsRetry(() => Sheets.Spreadsheets.get(SPREADSHEET_ID));
    const sheetObj = ssMeta.sheets.find(s => s.properties.title === sheetName);

    if (!sheetObj) {
      throw new Error(`Sheet ${sheetName} not found.`);
    }

    const sheetId = sheetObj.properties.sheetId;

    // Advanced Sheets Service (v4): DeleteDimensionRequest
    // API indices are 0-based. startIndex is inclusive, endIndex is exclusive.
    const requests = [
      {
        deleteDimension: {
          range: {
            sheetId: sheetId,
            dimension: "ROWS",
            startIndex: rowNumber - 1,
            endIndex: rowNumber
          }
        }
      }
    ];

    Sheets.Spreadsheets.batchUpdate({ requests: requests }, SPREADSHEET_ID);

    this._invalidateSheet(sheetName);
    return true;
  },

  // --- INTERNAL HELPER FUNCTIONS ---

  _rowsToRecords: function (values) {
    if (!values || values.length < 2) return [];
    const headers = values[0];
    const records = [];
    for (let i = 1; i < values.length; i++) {
      const row = values[i];
      if (!row || !row.join('').trim()) continue;
      let obj = {};
      headers.forEach((header, index) => {
        if (header) {
          const cleanKey = header.replace('*', '').trim();
          obj[cleanKey] = row[index] !== undefined ? row[index] : "";
        }
      });
      obj._rowNumber = i + 1;
      records.push(obj);
    }
    return records;
  },

  /** One Values.get for headers + next empty row (avoids 2 quota hits on create/update). */
  _getSheetMeta: function (sheetName) {
    const response = this._sheetsValuesGet(`${sheetName}!A1:AZ`);
    const values = response.values || [];
    const headers = values[0] || [];
    let nextRow = 2;
    for (let i = values.length - 1; i >= 0; i--) {
      if (values[i] && values[i][0]) {
        nextRow = i + 2;
        break;
      }
    }
    if (!values.length) nextRow = 2;
    return { headers: headers, values: values, nextRow: nextRow };
  },

  _getHeaders: function (sheetName) {
    return this._getSheetMeta(sheetName).headers;
  },

  _getNextRow: function (sheetName) {
    return this._getSheetMeta(sheetName).nextRow;
  },

  _scriptCache: function () {
    try {
      if (typeof CacheService !== 'undefined') return CacheService.getScriptCache();
    } catch (e) { /* ignore in tests */ }
    return null;
  },

  _cacheGet: function (key) {
    if (__dbMemCache[key] !== undefined) return __dbMemCache[key];
    const cache = this._scriptCache();
    if (!cache) return null;
    try {
      const raw = cache.get('lsc_db_' + key);
      if (!raw) return null;
      const parsed = JSON.parse(raw);
      __dbMemCache[key] = parsed;
      return parsed;
    } catch (e) {
      return null;
    }
  },

  _cachePut: function (key, value) {
    __dbMemCache[key] = value;
    const cache = this._scriptCache();
    if (!cache) return;
    try {
      const raw = JSON.stringify(value);
      // Script Cache max ~100KB per entry; skip oversized sheets silently
      if (raw.length < 90000) cache.put('lsc_db_' + key, raw, DB_READ_CACHE_TTL_SEC);
    } catch (e) { /* ignore */ }
  },

  _invalidateSheet: function (sheetName) {
    Object.keys(__dbMemCache).forEach((key) => {
      if (key === 'read:' + sheetName || key.indexOf(sheetName) !== -1) {
        delete __dbMemCache[key];
      }
    });
    const cache = this._scriptCache();
    if (!cache) return;
    try {
      cache.remove('lsc_db_read:' + sheetName);
      // Drop any batch keys that included this sheet (best-effort; TTL also covers it)
      Object.keys(__dbMemCache).forEach((key) => {
        if (key.indexOf('batch:') === 0) cache.remove('lsc_db_' + key);
      });
    } catch (e) { /* ignore */ }
  },

  _isQuotaError: function (err) {
    const msg = String(err && (err.message || err) || '');
    return /Quota exceeded|RATE_LIMIT|429|Read requests per minute/i.test(msg);
  },

  _withSheetsRetry: function (fn) {
    const maxAttempts = 5;
    let lastErr;
    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      try {
        return fn();
      } catch (err) {
        lastErr = err;
        if (!this._isQuotaError(err) || attempt === maxAttempts - 1) throw err;
        // Exponential backoff + jitter (Apps Script Utilities.sleep, ms)
        const waitMs = Math.min(30000, (Math.pow(2, attempt) * 1000) + Math.floor(Math.random() * 500));
        if (typeof Utilities !== 'undefined' && Utilities.sleep) Utilities.sleep(waitMs);
      }
    }
    throw lastErr;
  },

  _sheetsValuesGet: function (range) {
    return this._withSheetsRetry(() => Sheets.Spreadsheets.Values.get(SPREADSHEET_ID, range));
  },

  _sheetsValuesBatchGet: function (ranges) {
    return this._withSheetsRetry(() => Sheets.Spreadsheets.Values.batchGet(SPREADSHEET_ID, { ranges: ranges }));
  },

  _buildUpdateRanges: function (sheetName, rowNumber, headers, payloadObj) {
    const dataRanges = [];

    headers.forEach((header, index) => {
      // 1. If the header has a '*', skip it entirely to protect the formula
      if (header.includes('*')) return;

      // 2. Map the payload key (which won't have a '*')
      const cleanKey = header.trim();

      if (payloadObj.hasOwnProperty(cleanKey)) {
        const colLetter = this._indexToLetter(index + 1);
        dataRanges.push({
          range: `${sheetName}!${colLetter}${rowNumber}`,
          values: [[payloadObj[cleanKey]]]
        });
      }
    });

    return dataRanges;
  },

  _indexToLetter: colToLetter
};

/**
 * Universal 1-based column index to letter converter (e.g. 1 -> A, 27 -> AA).
 */
function colToLetter(column) {
  let temp, letter = '';
  while (column > 0) {
    temp = (column - 1) % 26;
    letter = String.fromCharCode(temp + 65) + letter;
    column = (column - temp - 1) / 26;
  }
  return letter;
}
const _colToLetter = colToLetter;

/**
 * Robust date parser supporting DD-MMM-YYYY, ISO strings, and standard dates.
 */
function parseSafeDate(dStr) {
  if (!dStr || dStr === 'N/A') return new Date("");
  if (dStr instanceof Date && !isNaN(dStr)) return dStr;
  let d = new Date(dStr);
  if (!isNaN(d)) return d;
  if (typeof dStr === 'string') {
    const parts = dStr.trim().split(/[\s\-\/\.]+/);
    const mMap = { jan: 0, feb: 1, mar: 2, apr: 3, may: 4, jun: 5, jul: 6, aug: 7, sep: 8, oct: 9, nov: 10, dec: 11 };
    if (parts.length >= 3) {
      if (parts[0].length === 4) {
        const y = parseInt(parts[0], 10);
        const m = isNaN(parts[1]) ? mMap[parts[1].toLowerCase()] : parseInt(parts[1], 10) - 1;
        const day = parseInt(parts[2], 10);
        if (m !== undefined && !isNaN(m) && !isNaN(day)) return new Date(y, m, day);
      }
      let y = parseInt(parts[2], 10);
      if (y < 100) y += 2000;
      const m = isNaN(parts[1]) ? mMap[parts[1].toLowerCase()] : parseInt(parts[1], 10) - 1;
      const day = parseInt(parts[0], 10);
      if (m !== undefined && !isNaN(m) && !isNaN(day)) return new Date(y, m, day);
    }
  }
  return new Date("");
}

/**
 * GAAP-compliant Daily Proration engine using UTC dates.
 * Distributes an amount across covered calendar months.
 *
 * @param {Date|string} sDateStr - Start date
 * @param {Date|string} eDateStr - End date
 * @param {Date|string} fallbackDateStr - Fallback date if start date is missing
 * @param {number} totalAmt - Total amount to distribute
 * @param {string} accrualMode - 'split' for daily proration, or 'anchor' for cash basis
 * @param {function(number, number, number)} onInterval - Callback receiving (year, monthIndex, intervalAmount)
 */
function distributeDailyProration(sDateStr, eDateStr, fallbackDateStr, totalAmt, accrualMode, onInterval) {
  let sDate = parseSafeDate(sDateStr);
  let eDate = parseSafeDate(eDateStr);
  if (isNaN(sDate)) sDate = parseSafeDate(fallbackDateStr);
  if (isNaN(sDate)) return;

  if (accrualMode === 'split' && !isNaN(eDate) && eDate >= sDate) {
    const start = new Date(sDate.getFullYear(), sDate.getMonth(), sDate.getDate());
    const end = new Date(eDate.getFullYear(), eDate.getMonth(), eDate.getDate());
    const msPerDay = 1000 * 60 * 60 * 24;
    const utcStart = Date.UTC(start.getFullYear(), start.getMonth(), start.getDate());
    const utcEnd = Date.UTC(end.getFullYear(), end.getMonth(), end.getDate());

    let totalDays = Math.floor((utcEnd - utcStart) / msPerDay) + 1;
    if (totalDays <= 0) totalDays = 1;

    const dailyRate = totalAmt / totalDays;
    let current = new Date(start);

    while (current <= end) {
      let cYear = current.getFullYear();
      let cMonth = current.getMonth();
      let endOfMonth = new Date(cYear, cMonth + 1, 0);
      let intervalEnd = (end < endOfMonth) ? end : endOfMonth;

      let utcCurrent = Date.UTC(current.getFullYear(), current.getMonth(), current.getDate());
      let utcIntervalEnd = Date.UTC(intervalEnd.getFullYear(), intervalEnd.getMonth(), intervalEnd.getDate());

      let daysInInterval = Math.floor((utcIntervalEnd - utcCurrent) / msPerDay) + 1;
      let intervalAmt = daysInInterval * dailyRate;

      onInterval(cYear, cMonth, intervalAmt);
      current = new Date(cYear, cMonth + 1, 1);
    }
  } else {
    // Anchor logic (cash basis)
    onInterval(sDate.getFullYear(), sDate.getMonth(), totalAmt);
  }
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    colToLetter,
    _colToLetter,
    parseSafeDate,
    distributeDailyProration,
    SPREADSHEET_ID,
    DB
  };
}

/**
 * API_Mutations.gs
 * Handles all CREATE and UPDATE operations from the frontend forms.
 */

function api_createRecord(sheetName, payload) {
  try {
    const gate = requireAnyViewPermission_();
    if (!gate.ok) return gate.response;
    const newRecord = DB.create(sheetName, payload);
    return { success: true, data: newRecord };
  } catch (error) {
    return { success: false, error: error.toString() };
  }
}

/**
 * Fully dynamic global dropdown API utility using Advanced Sheets Service.
 * Returns both the dropdown options and their exact structural usages (Tab/Column maps).
 */
function api_getGlobalDropdowns() {
  try {
    const gate = requireAnyViewPermission_();
    if (!gate.ok) return gate.response;
    const sheetName = 'DROP_DOWN';

    // 1. Fetch metadata columns A through G to find schemas
    const metaResponse = Sheets.Spreadsheets.Values.get(SPREADSHEET_ID, `'${sheetName}'!A:G`);
    const metaValues = metaResponse.values;

    if (!metaValues || metaValues.length < 2) {
      return { success: true, data: { options: {}, schemas: {} } };
    }

    const schemas = [];
    const schemaMetaMap = {};

    // Skip header row (index 0)
    for (let i = 1; i < metaValues.length; i++) {
      const row = metaValues[i];
      if (row[0] && row[0].toString().trim() !== '') {
        const schemaObj = {
          key: row[0],                              // e.g., 'status', 'batch'
          name: row[1],                             // e.g., 'Status'
          prefix: row[2],                           // e.g., 'STA'
          columns: row[3] ? JSON.parse(row[3]) : [], // [{key: 'id', label: 'ID'}, ...]
          usages: row[4] ? JSON.parse(row[4]) : [],  // [{tab: 'MEMBERS', column: 'status'}, ...]
          startCol: Number(row[5]),                 // 1-based start column index
          numCols: Number(row[6])                   // Total columns for this block
        };

        schemas.push(schemaObj);
        schemaMetaMap[schemaObj.key] = schemaObj;
      }
    }

    if (schemas.length === 0) {
      return { success: true, data: { options: {}, schemas: {} } };
    }

    // 2. Build batched ranges to fetch all option data blocks simultaneously
    const ranges = schemas.map(sch => {
      const startLetter = _colToLetter(sch.startCol);
      const endLetter = _colToLetter(sch.startCol + sch.numCols - 1);
      return `'${sheetName}'!${startLetter}3:${endLetter}200`;
    });

    const response = Sheets.Spreadsheets.Values.batchGet(SPREADSHEET_ID, { ranges: ranges });
    const globalOptions = {};

    if (response.valueRanges) {
      response.valueRanges.forEach((vr, i) => {
        const sch = schemas[i];
        const list = [];

        if (vr.values) {
          vr.values.forEach(row => {
            if (row[0] && row[0].toString().trim() !== '') {
              let obj = {};
              sch.columns.forEach((col, colIdx) => {
                obj[col.key] = row[colIdx] !== undefined ? row[colIdx] : '';
              });
              list.push(obj);
            }
          });
        }

        globalOptions[sch.key] = list;
      });
    }

    return {
      success: true,
      data: {
        options: globalOptions,     // Use this to populate dropdown lists in UI forms
        schemas: schemaMetaMap      // Use this to check usages, column maps, and prefixes dynamically
      }
    };

  } catch (error) {
    return { success: false, error: error.toString() };
  }
}


/**
 * Generates a prefixed unique ID.
 * @param {string} prefix - The module prefix (e.g., 'MEM', 'EXP', 'STF')
 * @return {string} A unique ID like "EXP-4B2C9A"
 */
function generateId(prefix) {
  const uniquePart = Utilities.getUuid().substring(0, 6).toUpperCase();
  return `${prefix}-${uniquePart}`;
}

/**
 * Next sequential member ID: LSC-MEM-1, LSC-MEM-2, ...
 * Also recognizes legacy MEM-<number> when computing the next value.
 */
function generateNextMemberId_() {
  const rows = (typeof DB !== 'undefined' && DB.read) ? (DB.read('MEMBERS') || []) : [];
  let max = 0;
  rows.forEach(function(row) {
    const id = String((row && row.memberId) || '').trim().toUpperCase();
    let match = id.match(/^LSC-MEM-(\d+)$/);
    if (!match) match = id.match(/^MEM-(\d+)$/);
    if (!match) return;
    const n = parseInt(match[1], 10);
    if (!isNaN(n) && n > max) max = n;
  });
  return 'LSC-MEM-' + (max + 1);
}

/**
 * Uploads a base64 encoded image to a Google Drive folder specified in the SETTINGS tab.
 * 
 * @param {string} base64Data - The base64 string (can include the "data:image/png;base64," prefix)
 * @param {string} filename - The desired name for the file (e.g., "MEM-1234.png")
 * @returns {object} { success: boolean, url: string, error: string }
 */
function api_uploadImageToDrive(base64Data, filename) {
  try {
    const gate = requireAnyViewPermission_();
    if (!gate.ok) return gate.response;
    if (!base64Data) throw new Error("No image data provided.");

    // 1. Fetch the DRIVE_ID from the SETTINGS tab
    // Assuming you have the DB utility from your architecture
    const settingsRows = DB.read('SETTINGS') || [];
    let driveId = '';

    const driveSetting = settingsRows.find(s => {
      const k = String(s.key || s.setting || s.Name || '').toLowerCase();
      return k === 'drive_id' || k === 'drive id';
    });

    if (driveSetting) {
      driveId = String(driveSetting.value || driveSetting.Value || '').trim();
    }

    if (!driveId && typeof LSC_DRIVE_ID !== 'undefined') {
      driveId = String(LSC_DRIVE_ID || '').trim();
    }

    if (!driveId) {
      throw new Error("DRIVE_ID is missing. Set it in config/env.json (driveId) or Settings → Database IDs.");
    }

    // 2. Parse and decode the Base64 string
    let data = base64Data;
    let contentType = 'image/png'; // Fallback default

    if (data.indexOf('data:') === 0) {
      const parts = data.split(',');
      const match = parts[0].match(/:(.*?);/);
      if (match && match.length > 1) contentType = match[1];
      data = parts[1];
    }

    const decodedData = Utilities.base64Decode(data);
    const safeFilename = filename ? filename : ('Upload_' + new Date().getTime());
    const blob = Utilities.newBlob(decodedData, contentType, safeFilename);

    // 3. Save to Google Drive
    const folder = DriveApp.getFolderById(driveId);
    const file = folder.createFile(blob);

    // 4. Set permissions so the frontend can render the image URL
    file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);

    // 5. Generate a direct view URL suitable for <img> tags
    const fileId = file.getId();
    const directUrl = `https://drive.google.com/uc?export=view&id=${fileId}`;

    return {
      success: true,
      url: directUrl,
      fileId: fileId,
      message: "Image uploaded successfully."
    };

  } catch (error) {
    return { success: false, error: error.toString() };
  }
}